root: C:\Users\Xardas\Dropbox\studies\diplom\system
chdir: C:\Users\Xardas\Dropbox\studies\diplom\system
pid: thin_ssl.pid
address: 0.0.0.0
timeout: 30
port: 4567
user: admin
group: admin
rackup: config.ru
log: thin.log
max_conns: 1024
max_persisten_conns: 512
daemonize: true