root: "/media/ssd/Users/Xardas/Dropbox/ruby projects/easedb"
chdir: "/media/ssd/Users/Xardas/Dropbox/ruby projects/easedb"
pid: thin.pid
address: 0.0.0.0
timeout: 30
port: 4568
user: xardas
group: xardas
rackup: config.ru
log: thin.log
max_conns: 1024
max_persisten_conns: 512
daemonize: false